#ifndef __SCANCODE_H__
#define __SCANCODE_H__

#include "../dev/types.h"

// KB Scancode Sets
enum ScancodeSet1
{
    S1_ESC_DOWN =                   0x01,
    S1_1_DOWN =                     0x02,
    S1_2_DOWN =                     0x03,
    S1_3_DOWN =                     0x04,
    S1_4_DOWN =                     0x05,
    S1_5_DOWN =                     0x06,
    S1_6_DOWN =                     0x07,
    S1_7_DOWN =                     0x08,
    S1_8_DOWN =                     0x09,
    S1_9_DOWN =                     0x0A,
    S1_0_DOWN =                     0x0B,
    S1_MINUS_DOWN =                 0x0C,
    S1_EQUAL_DOWN =                 0x0D,
    S1_BACKSPACE_DOWN =             0x0E,

    S1_TAB_DOWN =                   0x0F,
    S1_Q_DOWN =                     0x10,
    S1_W_DOWN =                     0x11,
    S1_E_DOWN =                     0x12,
    S1_R_DOWN =                     0x13,
    S1_T_DOWN =                     0x14,
    S1_Y_DOWN =                     0x15,
    S1_U_DOWN =                     0x16,
    S1_I_DOWN =                     0x17,
    S1_O_DOWN =                     0x18,
    S1_P_DOWN =                     0x19,
    S1_OPENSQUAREBRACKET_DOWN =     0x1A,
    S1_CLOSEDSQUAREBRACKET_DOWN =   0x1B,

    S1_ENTER_DOWN =                 0x1C,
    S1_LCTRL_DOWN =                 0x1D,

    S1_A_DOWN =                     0x1E,
    S1_S_DOWN =                     0x1F,
    S1_D_DOWN =                     0x20,
    S1_F_DOWN =                     0x21,
    S1_G_DOWN =                     0x22,
    S1_H_DOWN =                     0x23,
    S1_J_DOWN =                     0x24,
    S1_K_DOWN =                     0x25,
    S1_L_DOWN =                     0x26,
    S1_SEMICOLON_DOWN =             0x27,
    S1_SINGLEQUOTE_DOWN =           0x28,

    S1_BACKTICK_DOWN =              0x29,
    S1_LEFTSHIFT_DOWN =             0x2A,
    S1_BACKSLASH_DOWN =             0x2B,

    S1_Z_DOWN =                     0x2C,
    S1_X_DOWN =                     0x2D,
    S1_C_DOWN =                     0x2E,
    S1_V_DOWN =                     0x2F,
    S1_B_DOWN =                     0x30,
    S1_N_DOWN =                     0x31,
    S1_M_DOWN =                     0x32,
    S1_COMMA_DOWN =                 0x33,
    S1_PERIOD_DOWN =                0x34,
    S1_SLASH_DOWN =                 0x35,
    S1_RSHIFT_DOWN =                0x36,
    S1_KEYPAD_ASTERISK_DOWN =       0x37,
    S1_LALT_DOWN =                  0x38,
    S1_SPACE_DOWN =                 0x39,
    S1_CAPSLOCK_DOWN =              0x3A,

    S1_F1_DOWN =                    0x3B,
    S1_F2_DOWN =                    0x3C,
    S1_F3_DOWN =                    0x3D,
    S1_F4_DOWN =                    0x3E,
    S1_F5_DOWN =                    0x3F,
    S1_F6_DOWN =                    0x40,
    S1_F7_DOWN =                    0x41,
    S1_F8_DOWN =                    0x42,
    S1_F9_DOWN =                    0x43,
    S1_F10_DOWN =                   0x44,
    S1_NUMLOCK_DOWN =               0x45,
    S1_SCROLLLOCK_DOWN =            0x46,

    S1_KEYPAD_7_DOWN =              0x47,
    S1_KEYPAD_8_DOWN =              0x48,
    S1_KEYPAD_9_DOWN =              0x49,
    S1_KEYPAD_MINUS_DOWN =          0x4A,
    S1_KEYPAD_4_DOWN =              0x4B,
    S1_KEYPAD_5_DOWN =              0x4C,
    S1_KEYPAD_6_DOWN =              0x4D,
    S1_KEYPAD_PLUS_DOWN =           0x4E,
    S1_KEYPAD_1_DOWN =              0x4F,
    S1_KEYPAD_2_DOWN =              0x50,
    S1_KEYPAD_3_DOWN =              0x51,
    S1_KEYPAD_0_DOWN =              0x52,
    S1_KEYPAD_PERIOD_DOWN =         0x53,

    S1_F11_DOWN =                   0x57,
    S1_F12_DOWN =                   0x58,

    S1_ESC_UP =                   0x81,
    S1_1_UP =                     0x82,
    S1_2_UP =                     0x83,
    S1_3_UP =                     0x84,
    S1_4_UP =                     0x85,
    S1_5_UP =                     0x86,
    S1_6_UP =                     0x87,
    S1_7_UP =                     0x88,
    S1_8_UP =                     0x89,
    S1_9_UP =                     0x8A,
    S1_0_UP =                     0x8B,
    S1_MINUS_UP =                 0x8C,
    S1_EQUAL_UP =                 0x8D,
    S1_BACKSPACE_UP =             0x8E,

    S1_TAB_UP =                   0x8F,
    S1_Q_UP =                     0x90,
    S1_W_UP =                     0x91,
    S1_E_UP =                     0x92,
    S1_R_UP =                     0x93,
    S1_T_UP =                     0x94,
    S1_Y_UP =                     0x95,
    S1_U_UP =                     0x96,
    S1_I_UP =                     0x97,
    S1_O_UP =                     0x98,
    S1_P_UP =                     0x99,
    S1_OPENSQUAREBRACKET_UP =     0x9A,
    S1_CLOSEDSQUAREBRACKET_UP =   0x9B,

    S1_ENTER_UP =                 0x9C,
    S1_LCTRL_UP =                 0x9D,
    S1_A_UP =                     0x9E,
    S1_S_UP =                     0x9F,
    S1_D_UP =                     0xA0,
    S1_F_UP =                     0xA1,
    S1_G_UP =                     0xA2,
    S1_H_UP =                     0xA3,
    S1_J_UP =                     0xA4,
    S1_K_UP =                     0xA5,
    S1_L_UP =                     0xA6,
    S1_SEMICOLON_UP =             0xA7,
    S1_SINGLEQUOTE_UP =           0xA8,

    S1_BACKTICK_UP =              0xA9,
    S1_LEFTSHIFT_UP =             0xAA,
    S1_BACKSLASH_UP =             0xAB,
    S1_Z_UP =                     0xAC,
    S1_X_UP =                     0xAD,
    S1_C_UP =                     0xAE,
    S1_V_UP =                     0xAF,
    S1_B_UP =                     0xB0,
    S1_N_UP =                     0xB1,
    S1_M_UP =                     0xB2,
    S1_COMMA_UP =                 0xB3,
    S1_PERIOD_UP =                0xB4,
    S1_SLASH_UP =                 0xB5,
    S1_RSHIFT_UP =                0xB6,
    S1_KEYPAD_ASTERISK_UP =       0xB7,
    S1_LALT_UP =                  0xB8,
    S1_SPACE_UP =                 0xB9,
    S1_CAPSLOCK_UP =              0xBA,

    S1_F1_UP =                    0xBB,
    S1_F2_UP =                    0xBC,
    S1_F3_UP =                    0xBD,
    S1_F4_UP =                    0xBE,
    S1_F5_UP =                    0xBF,
    S1_F6_UP =                    0xC0,
    S1_F7_UP =                    0xC1,
    S1_F8_UP =                    0xC2,
    S1_F9_UP =                    0xC3,
    S1_F10_UP =                   0xC4,

    S1_NUMLOCK_UP =               0xC5,
    S1_SCROLLLOCK_UP =            0xC6,

    S1_KEYPAD_7_UP =              0xC7,
    S1_KEYPAD_8_UP =              0xC8,
    S1_KEYPAD_9_UP =              0xC9,
    S1_KEYPAD_MINUS_UP =          0xCA,
    S1_KEYPAD_4_UP =              0xCB,
    S1_KEYPAD_5_UP =              0xCC,
    S1_KEYPAD_6_UP =              0xCD,
    S1_KEYPAD_PLUS_UP =           0xCE,
    S1_KEYPAD_1_UP =              0xCF,
    S1_KEYPAD_2_UP =              0xD0,
    S1_KEYPAD_3_UP =              0xD1,
    S1_KEYPAD_0_UP =              0xD2,
    S1_KEYPAD_PERIOD_UP =         0xD3,

    S1_F11_UP =                   0xD7,
    S1_F12_UP =                   0xD8,
};

enum ScancodeSet2
{
    S2_F9_DOWN = 0x01
};


#endif