// #include "disk.c"
#include "memory.c"
#include "asm.c"
#include "wait.c"
#include "util.c"
#include "hash.c"
#include "ata.c"
#include "pit.c"
#include "idt.c"
#include "pci.c"
#include "gdt.c"
#include "interrupts/pcspkr.c"